# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.1"
manifest_format = "2.0"
project_hash = "cbdb6d0cdff2104c6f4df24ebfbb8db7249b7d49"

[[deps.Philote]]
path = "."
uuid = "8b8e1234-5678-90ab-cdef-123456789abc"
version = "0.1.0"
