name = "Philote"
uuid = "b1df2f05-6566-432e-bbeb-89bf4b62cd85"
keywords = ["MDO", "multidisciplinary", "optimization", "engineering", "design"]
license = "Apache-2.0"
version = "0.0.0"
authors = ["Christopher Lupp"]
description = "Julia interface for defining MDO (Multidisciplinary Design Optimization) disciplines using the Philote framework"
repository = "https://github.com/MDO-Standards/Philote-Julia.git"

[deps]
ProtoBuf = "3349acd9-ac6a-5e09-bcdb-63829b23a429"
gRPCClient2 = "b7a07a73-68ea-4538-9481-8488798afd91"

[compat]
gRPCClient2 = "0.1.1"
julia = "1.11, 1.12"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "JuliaFormatter"]
