name = "Philote"
uuid = "b1df2f05-6566-432e-bbeb-89bf4b62cd85"
authors = ["Christopher Lupp"]
version = "0.1.0"
description = "Julia interface for defining MDO (Multidisciplinary Design Optimization) disciplines using the Philote framework"
license = "Apache-2.0"
repository = "https://github.com/MDO-Standards/Philote-Julia.git"
keywords = ["MDO", "multidisciplinary", "optimization", "engineering", "design"]

[deps]
ProtoBuf = "3349acd9-ac6a-5e09-bcdb-63829b23a429"
gRPCClient2 = "655190db-73ea-4678-9984-625c41784ebb"

[compat]
julia = "1.6, 1.7, 1.8, 1.9, 1.10, 1.11"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "JuliaFormatter"]
