# Autogenerated using ProtoBuf.jl v1.2.0 on 2025-11-06T15:36:24.442
# original file: /Users/clupp/tools/Philote/Philote-Python/proto/data.proto (proto3 syntax)

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export var"#DataType", StreamOptions, PartialsMetaData, VariableType, DisciplineOptions
export DisciplineProperties, OptionsList, var"#Array", VariableMetaData

@enumx var"#DataType" kBool=0 kInt=1 kDouble=2 kString=3

struct StreamOptions
    num_double::Int64
end
StreamOptions(; num_double=zero(Int64)) = StreamOptions(num_double)
PB.default_values(::Type{StreamOptions}) = (; num_double=zero(Int64))
PB.field_numbers(::Type{StreamOptions}) = (; num_double=1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:StreamOptions})
    num_double = zero(Int64)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            num_double = PB.decode(d, Int64)
        else
            Base.skip(d, wire_type)
        end
    end
    return StreamOptions(num_double)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::StreamOptions)
    initpos = position(e.io)
    x.num_double != zero(Int64) && PB.encode(e, 1, x.num_double)
    return position(e.io) - initpos
end
function PB._encoded_size(x::StreamOptions)
    encoded_size = 0
    x.num_double != zero(Int64) && (encoded_size += PB._encoded_size(x.num_double, 1))
    return encoded_size
end

struct PartialsMetaData
    name::String
    subname::String
    shape::Vector{Int64}
end
function PartialsMetaData(; name="", subname="", shape=Vector{Int64}())
    PartialsMetaData(name, subname, shape)
end
PB.default_values(::Type{PartialsMetaData}) = (; name="", subname="", shape=Vector{Int64}())
PB.field_numbers(::Type{PartialsMetaData}) = (; name=1, subname=2, shape=3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:PartialsMetaData})
    name = ""
    subname = ""
    shape = PB.BufferedVector{Int64}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            name = PB.decode(d, String)
        elseif field_number == 2
            subname = PB.decode(d, String)
        elseif field_number == 3
            PB.decode!(d, wire_type, shape)
        else
            Base.skip(d, wire_type)
        end
    end
    return PartialsMetaData(name, subname, shape[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::PartialsMetaData)
    initpos = position(e.io)
    !isempty(x.name) && PB.encode(e, 1, x.name)
    !isempty(x.subname) && PB.encode(e, 2, x.subname)
    !isempty(x.shape) && PB.encode(e, 3, x.shape)
    return position(e.io) - initpos
end
function PB._encoded_size(x::PartialsMetaData)
    encoded_size = 0
    !isempty(x.name) && (encoded_size += PB._encoded_size(x.name, 1))
    !isempty(x.subname) && (encoded_size += PB._encoded_size(x.subname, 2))
    !isempty(x.shape) && (encoded_size += PB._encoded_size(x.shape, 3))
    return encoded_size
end

@enumx VariableType kInput=0 kDiscreteInput=1 kResidual=2 kOutput=3 kDiscreteOutput=4 kPartial=5

struct DisciplineOptions
    options::Union{Nothing, google.protobuf.Struct}
end
DisciplineOptions(; options=nothing) = DisciplineOptions(options)
PB.default_values(::Type{DisciplineOptions}) = (; options=nothing)
PB.field_numbers(::Type{DisciplineOptions}) = (; options=1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:DisciplineOptions})
    options = Ref{Union{Nothing, google.protobuf.Struct}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, options)
        else
            Base.skip(d, wire_type)
        end
    end
    return DisciplineOptions(options[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::DisciplineOptions)
    initpos = position(e.io)
    !isnothing(x.options) && PB.encode(e, 1, x.options)
    return position(e.io) - initpos
end
function PB._encoded_size(x::DisciplineOptions)
    encoded_size = 0
    !isnothing(x.options) && (encoded_size += PB._encoded_size(x.options, 1))
    return encoded_size
end

struct DisciplineProperties
    continuous::Bool
    differentiable::Bool
    provides_gradients::Bool
    name::String
    version::String
end
function DisciplineProperties(;
    continuous=false, differentiable=false, provides_gradients=false, name="", version=""
)
    DisciplineProperties(continuous, differentiable, provides_gradients, name, version)
end
function PB.default_values(::Type{DisciplineProperties})
    (;
        continuous=false,
        differentiable=false,
        provides_gradients=false,
        name="",
        version="",
    )
end
function PB.field_numbers(::Type{DisciplineProperties})
    (; continuous=1, differentiable=2, provides_gradients=3, name=4, version=5)
end

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:DisciplineProperties})
    continuous = false
    differentiable = false
    provides_gradients = false
    name = ""
    version = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            continuous = PB.decode(d, Bool)
        elseif field_number == 2
            differentiable = PB.decode(d, Bool)
        elseif field_number == 3
            provides_gradients = PB.decode(d, Bool)
        elseif field_number == 4
            name = PB.decode(d, String)
        elseif field_number == 5
            version = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return DisciplineProperties(
        continuous, differentiable, provides_gradients, name, version
    )
end

function PB.encode(e::PB.AbstractProtoEncoder, x::DisciplineProperties)
    initpos = position(e.io)
    x.continuous != false && PB.encode(e, 1, x.continuous)
    x.differentiable != false && PB.encode(e, 2, x.differentiable)
    x.provides_gradients != false && PB.encode(e, 3, x.provides_gradients)
    !isempty(x.name) && PB.encode(e, 4, x.name)
    !isempty(x.version) && PB.encode(e, 5, x.version)
    return position(e.io) - initpos
end
function PB._encoded_size(x::DisciplineProperties)
    encoded_size = 0
    x.continuous != false && (encoded_size += PB._encoded_size(x.continuous, 1))
    x.differentiable != false && (encoded_size += PB._encoded_size(x.differentiable, 2))
    x.provides_gradients != false &&
        (encoded_size += PB._encoded_size(x.provides_gradients, 3))
    !isempty(x.name) && (encoded_size += PB._encoded_size(x.name, 4))
    !isempty(x.version) && (encoded_size += PB._encoded_size(x.version, 5))
    return encoded_size
end

struct OptionsList
    options::Vector{String}
    var"#type"::Vector{var"#DataType".T}
end
function OptionsList(; options=Vector{String}(), var"#type"=Vector{var"#DataType".T}())
    OptionsList(options, var"#type")
end
function PB.default_values(::Type{OptionsList})
    (; options=Vector{String}(), var"#type"=Vector{var"#DataType".T}())
end
PB.field_numbers(::Type{OptionsList}) = (; options=1, var"#type"=2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:OptionsList})
    options = PB.BufferedVector{String}()
    var"#type" = PB.BufferedVector{var"#DataType".T}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, options)
        elseif field_number == 2
            PB.decode!(d, wire_type, var"#type")
        else
            Base.skip(d, wire_type)
        end
    end
    return OptionsList(options[], var"#type"[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::OptionsList)
    initpos = position(e.io)
    !isempty(x.options) && PB.encode(e, 1, x.options)
    !isempty(x.var"#type") && PB.encode(e, 2, x.var"#type")
    return position(e.io) - initpos
end
function PB._encoded_size(x::OptionsList)
    encoded_size = 0
    !isempty(x.options) && (encoded_size += PB._encoded_size(x.options, 1))
    !isempty(x.var"#type") && (encoded_size += PB._encoded_size(x.var"#type", 2))
    return encoded_size
end

struct var"#Array"
    name::String
    subname::String
    start::Int64
    var"#end"::Int64
    var"#type"::VariableType.T
    data::Vector{Float64}
end
function var"#Array"(;
    name="",
    subname="",
    start=zero(Int64),
    var"#end"=zero(Int64),
    var"#type"=VariableType.kInput,
    data=Vector{Float64}(),
)
    var"#Array"(name, subname, start, var"#end", var"#type", data)
end
function PB.default_values(::Type{var"#Array"})
    (;
        name="",
        subname="",
        start=zero(Int64),
        var"#end"=zero(Int64),
        var"#type"=VariableType.kInput,
        data=Vector{Float64}(),
    )
end
function PB.field_numbers(::Type{var"#Array"})
    (; name=1, subname=2, start=3, var"#end"=4, var"#type"=5, data=6)
end

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:var"#Array"})
    name = ""
    subname = ""
    start = zero(Int64)
    var"#end" = zero(Int64)
    var"#type" = VariableType.kInput
    data = PB.BufferedVector{Float64}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            name = PB.decode(d, String)
        elseif field_number == 2
            subname = PB.decode(d, String)
        elseif field_number == 3
            start = PB.decode(d, Int64)
        elseif field_number == 4
            var"#end" = PB.decode(d, Int64)
        elseif field_number == 5
            var"#type" = PB.decode(d, VariableType.T)
        elseif field_number == 6
            PB.decode!(d, wire_type, data)
        else
            Base.skip(d, wire_type)
        end
    end
    return var"#Array"(name, subname, start, var"#end", var"#type", data[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::var"#Array")
    initpos = position(e.io)
    !isempty(x.name) && PB.encode(e, 1, x.name)
    !isempty(x.subname) && PB.encode(e, 2, x.subname)
    x.start != zero(Int64) && PB.encode(e, 3, x.start)
    x.var"#end" != zero(Int64) && PB.encode(e, 4, x.var"#end")
    x.var"#type" != VariableType.kInput && PB.encode(e, 5, x.var"#type")
    !isempty(x.data) && PB.encode(e, 6, x.data)
    return position(e.io) - initpos
end
function PB._encoded_size(x::var"#Array")
    encoded_size = 0
    !isempty(x.name) && (encoded_size += PB._encoded_size(x.name, 1))
    !isempty(x.subname) && (encoded_size += PB._encoded_size(x.subname, 2))
    x.start != zero(Int64) && (encoded_size += PB._encoded_size(x.start, 3))
    x.var"#end" != zero(Int64) && (encoded_size += PB._encoded_size(x.var"#end", 4))
    x.var"#type" != VariableType.kInput &&
        (encoded_size += PB._encoded_size(x.var"#type", 5))
    !isempty(x.data) && (encoded_size += PB._encoded_size(x.data, 6))
    return encoded_size
end

struct VariableMetaData
    var"#type"::VariableType.T
    name::String
    shape::Vector{Int64}
    units::String
end
function VariableMetaData(;
    var"#type"=VariableType.kInput, name="", shape=Vector{Int64}(), units=""
)
    VariableMetaData(var"#type", name, shape, units)
end
function PB.default_values(::Type{VariableMetaData})
    (; var"#type"=VariableType.kInput, name="", shape=Vector{Int64}(), units="")
end
PB.field_numbers(::Type{VariableMetaData}) = (; var"#type"=1, name=3, shape=4, units=5)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:VariableMetaData})
    var"#type" = VariableType.kInput
    name = ""
    shape = PB.BufferedVector{Int64}()
    units = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            var"#type" = PB.decode(d, VariableType.T)
        elseif field_number == 3
            name = PB.decode(d, String)
        elseif field_number == 4
            PB.decode!(d, wire_type, shape)
        elseif field_number == 5
            units = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return VariableMetaData(var"#type", name, shape[], units)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::VariableMetaData)
    initpos = position(e.io)
    x.var"#type" != VariableType.kInput && PB.encode(e, 1, x.var"#type")
    !isempty(x.name) && PB.encode(e, 3, x.name)
    !isempty(x.shape) && PB.encode(e, 4, x.shape)
    !isempty(x.units) && PB.encode(e, 5, x.units)
    return position(e.io) - initpos
end
function PB._encoded_size(x::VariableMetaData)
    encoded_size = 0
    x.var"#type" != VariableType.kInput &&
        (encoded_size += PB._encoded_size(x.var"#type", 1))
    !isempty(x.name) && (encoded_size += PB._encoded_size(x.name, 3))
    !isempty(x.shape) && (encoded_size += PB._encoded_size(x.shape, 4))
    !isempty(x.units) && (encoded_size += PB._encoded_size(x.units, 5))
    return encoded_size
end
