# Autogenerated using ProtoBuf.jl v1.2.0 on 2025-11-06T15:36:24.442
# original file: /Users/clupp/tools/Philote/Philote-Python/proto/disciplines.proto (proto3 syntax)

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx



# TODO: SERVICE
#    ImplicitService

# TODO: SERVICE
#    ExplicitService

# TODO: SERVICE
#    DisciplineService
